import {useEffect,useRef,useState} from 'react';
import {Upload,Trash2,Send,Sun,Moon,ThumbsUp,ThumbsDown,FileText,Image as ImageIcon,BarChart3} from 'lucide-react';
const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000';
type Doc={id:string;name:string;status:string;progress:number;page_count:number;size_bytes:number};
type Citation={doc_name:string;page:number;snippet:string;image_url?:string;score:number};
type Result={answer:string;citations:Citation[];confidence:number;confidence_label:string;timings_ms:Record<string,number>;not_found:boolean};
export default function App(){const [docs,setDocs]=useState<Doc[]>([]),[selected,setSelected]=useState<string[]>([]),[q,setQ]=useState(''),[messages,setMessages]=useState<any[]>([]),[dark,setDark]=useState(true),[source,setSource]=useState<Citation|null>(null),input=useRef<HTMLInputElement>(null);
 const load=async()=>setDocs(await fetch(API+'/api/documents').then(r=>r.json())); useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[]);
 const upload=async(e:any)=>{for(const f of [...e.target.files]){const d=new FormData();d.append('file',f);await fetch(API+'/api/documents/upload',{method:'POST',body:d})}load()};
 const del=async(id:string)=>{await fetch(API+'/api/documents/'+id,{method:'DELETE'});load()};
 const ask=async()=>{if(!q.trim())return;const question=q;setQ('');setMessages((m)=>[...m,{role:'user',text:question}]);const r=await fetch(API+'/api/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,top_k:5,filters:selected.length?{doc_ids:selected}:undefined})});const data:Result=await r.json();setMessages(m=>[...m,{role:'assistant',data}]);setSource(data.citations[0]||null)};
 return <div className={dark?'app dark':'app'}><header><div><b>DocuRAG</b><span> Multimodal RAG</span></div><button onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></header><main className="grid"><aside><div className="panel"><h3>Documents</h3><label className="drop"><Upload/><span>Drop PDFs / images</span><input ref={input} type="file" multiple accept=".pdf,.png,.jpg,.jpeg" onChange={upload}/></label>{docs.map(d=><div className="doc" key={d.id}><input type="checkbox" checked={selected.includes(d.id)} onChange={e=>setSelected(e.target.checked?[...selected,d.id]:selected.filter(x=>x!==d.id))}/><FileText size={16}/><div className="grow"><b>{d.name}</b><small>{d.status} · {d.progress}%</small></div><button onClick={()=>del(d.id)}><Trash2 size={15}/></button></div>)}</div></aside><section className="panel chat"><div className="messages">{messages.length===0&&<div className="empty"><ImageIcon size={42}/><h2>Ask your documents</h2><p>Search text, tables, figures, charts and scanned pages.</p></div>}{messages.map((m,i)=>m.role==='user'?<div className="bubble user" key={i}>{m.text}</div>:<div className="answer" key={i}><div className="bubble">{m.data.answer}</div><div className="meta"><b>{m.data.confidence_label}</b> confidence · {m.data.timings_ms.total} ms</div><div className="citations">{m.data.citations.map((c:Citation,j:number)=><button onClick={()=>setSource(c)} key={j}>[{c.doc_name}, p.{c.page}]</button>)}</div><div className="feedback"><ThumbsUp size={15}/><ThumbsDown size={15}/></div></div>)}</div><div className="composer"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Ask a question about your documents…"/><button onClick={ask}><Send size={18}/></button></div></section><aside><div className="panel source"><h3><BarChart3 size={17}/> Source viewer</h3>{source?<><div className="sourceTitle">{source.doc_name} · page {source.page}</div>{source.image_url&&<img src={API+source.image_url}/>}<p>{source.snippet}</p><div className="score">Retrieval score {source.score.toFixed(3)}</div></>:<div className="empty"><FileText/><p>Select a citation to inspect its source.</p></div>}</div></aside></main></div>}
